### ISSUE TITLE
`is` doesn't get filled with non-numeric queries

### ISSUE THREAD

**Issue by deadNightTiger** [AlecAivazis/redux-responsive#101]
For example, if I add to default breakpoints `{ print: "print" }`, then `browser.is.print` is always false, even when `browser.mediaType` is `print`.

**Comment by AlecAivazis** [comment]
Thanks fore reporting this @deadNightTiger. Looks like the issue is some leftovers from old logic (the comments haven't even been updated 🤦‍♂️): https://github.com/AlecAivazis/redux-responsive/blob/master/src/util/createReducer.js#L104-L106

Should be easy to fix since we are no longer checking for greater than, and instead just relying on the `mediaType` arg. If you want to submit a PR, i can take a look today otherwise I'll try to get to it over the weekend

**Comment by AlecAivazis** [comment]
@deadNightTiger - i just pushed a PR that should fix this. Mind taking a look? https://github.com/AlecAivazis/redux-responsive/pull/108
