### ISSUE TITLE
Are there any breaking changes in 2.0?

### ISSUE THREAD

**Issue by ratson** [AlecAivazis/redux-responsive#19]
As a v1 user, I am wondering what have been changed and how to do the upgrade.
It would be great if this could be documented in CHANGELOG.

**Comment by AlecAivazis** [comment]
Oh, sorry for not adding a changelog - I'll make one ASAP. The only change was that options are now passed to the `createResponsiveStoreEnhancer` via an object instead of just an argument. The reason for this is that an additional argument was added for better isomorphic support. You can see the full discussion here #17 and #18.

**Comment by AlecAivazis** [comment]
I've added a changelog to the wiki. Hope this help explain the changes and how to migrate to the new API. Sorry for any humps this caused.

**Comment by ratson** [comment]
Thanks
