### ISSUE TITLE
Make it optional with width and height to only use matchMedia

### ISSUE THREAD

**Issue by EloB** [AlecAivazis/redux-responsive#22]
For of all I would like to thank for a good library.

I read through your codebase and saw that you used `window.matchMedia`. This was the reason that I started using this library but found out that you also listen to `window.onresize` (addEventListener) probably because you want to store the `width` and `height` inside `redux`. So you dispatch a lot of `CALCULATE_RESPONSIVE_STATE`. The `width`and `height` is probably not used very often and could be `opt-in`. If you only dispatch when the matchMedia triggers you will lower the amount of dispatches that will increase performance on big applications.

*Example code to listen on a matchMedia*
```
var mql = window.matchMedia("(orientation: portrait)");
mql.addListener(handleOrientationChange);
handleOrientationChange(mql);
```

https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Testing_media_queries

**Comment by AlecAivazis** [comment]
Hey @EloB,

Thanks for turning me onto the media query event-handlers, that would make this library much more efficient. I'm a bit concerned about removing height and width from the state as that would result in another API breaking change (and another major release just after v2.0 came out). One alternative is to add a `performance_mode` flag (default off) that would remove `height` and `width` from the state as well as add the more efficient event handler.

If you wanted to submit a PR, I would be very happy to review it. Otherwise, I will try to work out an implementation soon.

**Comment by EloB** [comment]
Yeah that sounds like a good idea! If I got time I could sit on my spare time.

**Comment by EloB** [comment]
A good solution would be to only listen the current active mediaObject and then dispatch when it changes. Iterate over all the mediaObject.matches and build the new state and then listen to the new active mediaObject and stop listen to the previous mediaObject.

**Comment by acidicX** [comment]
It would be really great to have this. I only use redux-responsive for breakpoint changes, using only matchMedia would be much more efficient for my project.

**Comment by AlecAivazis** [comment]
@EloB @acidicX - i started working on this last night and should have something ready in a few days. Thanks against @EloB for pointing this out.

**Comment by AlecAivazis** [comment]
I'm going to close this even tho height/width are still present for backward compatibility. They will be removed once I feel comfortable with the stability of performance mode

**Comment by AlecAivazis** [comment]
@EloB i just published the merged changes, please let me know if you run into any problems
