### ISSUE TITLE
Debouce on resize

### ISSUE THREAD

**Issue by gustavorino** [AlecAivazis/redux-responsive#29]
This reducer is great, i've added already to my boilerplate project.

There is one thing i would like to mention. When the browser is resized manually the middleware dispatches dozens of actions, which makes the browser very slow ( almost freezes it ). Adding a debounce parameter option would be a good idea.

**Comment by AlecAivazis** [comment]
Hey @gustavorino, thanks for the kind words.

There is already an option for setting a throttleTime. The default value is 100ms but if you are running into performance issues, I suggest increasing the default value. You have to use the store enhancer factory `createResponsiveStoreEnhancer`:

```
import {createStore} from 'redux'
import {createResponsiveStoreEnhancer} from 'redux-responsive'
import reducer from './reducer'

const store = createStore(
                    reducer,
                    createResponsiveStoreEnhancer({throttleTime: 250}))
```

Sometime in the future, I should do some actual performance tests to try to find the "best" value. I haven't noticed any performance issues on my laptop with the default values but I haven't really tried to push the limits.

A little note: I used throttle instead of debounce to better emulate the css behavior.

**Comment by gustavorino** [comment]
Wow! sorry i didnt see that earlier!  Thank you!

**Comment by AlecAivazis** [comment]
np @gustavorino! Please let me know if you run into any more hiccups.
