### ISSUE TITLE
replace "infinity" with a maximum value

### ISSUE THREAD

**Issue by dawidvdh** [AlecAivazis/redux-responsive#46]
Hey,

I was just wondering if there was anyway to replace the infinity key/value with a maximum of a sort, as i am currently using mediaType to define which size of image loads (small, medium, large) but when the window scale is beyond large it goes to infinity...

Any Help would be Greatly Appreciated.

**Comment by AlecAivazis** [comment]
Since the breakpoints you list in the object are the upper bounds, there will always be the breakpoints bigger than the largest you've specified. I guess another way to say that is that infinity is always a breakpoint, but you can never be greater than it. Currently there is no way to set the name for the infinity breakpoint but that is definitely a reasonable thing to add to the enhancer factory.  

Until I get around to it (feel free to submit a PR ;) ) you should be able to do what you want with something like `browser.mediaType == 'large' || browser.greaterThan.large`. Please let me know if you have any more questions.

**Comment by AlecAivazis** [comment]
@dawidvdh this has now been fixed by PR #54.
