### ISSUE TITLE
Idea: Add devicePixelRatio

### ISSUE THREAD

**Issue by ivoanastacio** [AlecAivazis/redux-responsive#53]
Hi,

I can submit a PR but before I would like to know if someone else finds it useful to also have the current devicePixelRatio, obtained from the window object.

My current use case for it is that I need to build urls for responsive images with more or less resolution, depending on the current devicePixelRatio.

[caniuse: devicePixelRatio](http://caniuse.com/#search=devicePixelRatio)
[MDN: Window.devicePixelRatio](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio)

Kind regards,
Ivo

**Comment by AlecAivazis** [comment]
Hey @ivoanastacio, nice idea! I think you've brought up an interesting question about the package in general but before I begin my rant I should ask: if all you're intesrested in is the current value when the width changes, it should be as easy as just having `window.devicePixelRatio` in your `render` function (or stateless component). If that answers your question, please skip the following rabbit hole:

If that's not your question, I think your question could be generalized to: "should `redux-responsive` have listeners/store various browser attributes besides the media state?" I have been thinking about this a lot lately so excuse me if this reply goes a bit long.

I myself ran into this problem when i added `performanceMode` because `width` was no longer updating when the browser resized, only when the media state changed. However, there are some very creative applications of `redux-responsive` which rely on it so I opted to leave `width` in and leave `performanceMode` optional in order to avoid more breaking changes. It didn't occur to me that this would be a problem with other window listeners/attributes.

In general, adding any given event listener on a case-by-case basis can actually be pretty challenging - you have to build you own reducer composed of the one from `redux-responsive`  and something to track whatever value you're interested in. You then have to build a store enchancer which isn't too hard - you can basically copy the code straight out of  `src/util/addThrottledHandlers.js` and add it to your application.

What I think the right thing to do here is provide some sort of way of making this easier for people to do. I don't want to overcomplicate the API so if its no easier than the above described process, it's probably not worth the trouble. If this sounds like something you're interested in @ivoanastacio, I'd love to hear your thoughts on a way to generalize the logic.

cc @montemishkin

**Comment by AlecAivazis** [comment]
@ivoanastacio you should now be able to do this using a custom defined field as soon as #60 gets approved/merged in

**Comment by AlecAivazis** [comment]
Closing this since the PR was merged
