### ISSUE TITLE
why Skip the serverside when that is the most important use for this?

### ISSUE THREAD

**Issue by joeLloyd** [AlecAivazis/redux-responsive#69]
storing that info server side means you could send different layouts or more/less centered components to the client. why was this blocked?

**Comment by AlecAivazis** [comment]
@joeLloyd, thanks for taking the time to post an issue. Unfortunately, I don't quite understand what you are asking. There is full support for server side rendering as described in the reader. Please let me know if theees something I could add for better support.

**Comment by joeLloyd** [comment]
Sorry, I'll try to be more clear. 

From what I understand on the server nothing is added to redux, is this correct?
if not perhaps I'm not doing it right.

**Comment by AlecAivazis** [comment]
Hmm I'm still having some trouble knowing where to direct you. Are you trying to set the initial media type on the server so that the UI matches the client? If so, you can do that by setting the `initialMediaType` value of the reducer factory. There is also a section for "Server side rendering" on the README which describes all of this.

**Comment by AlecAivazis** [comment]
@joeLloyd I'm going to close this to keep things tidy. Please feel free to continue conversation here and I can reopen it later when I know how to better support what you're trying to accomplish. Thanks again for the issue and please let me know if you run into any more problems
