### ISSUE TITLE
browser.orientation not changing on changing device orientation.

### ISSUE THREAD

**Issue by VeeteshJain** [AlecAivazis/redux-responsive#78]
Hi @AlecAivazis 
seems you read orientation when ```calculateResponsiveState``` runs, but we don't listen to orientation change window event.

if we need to do calculateResponsiveState on orientation change event so plz update that in the readme.

**Comment by AlecAivazis** [comment]
Hey @VeeteshJain thanks for pointing this out, I don't do much mobile development lately so I haven't really worked with devices whose orientation could change. I think since `orientation` is in the responsive state, one would expect it to update like the rest of the state. 

If you wanted to submit a PR, I would gladly review it. it "should" be pretty straightforward to add it [here](https://github.com/AlecAivazis/redux-responsive/blob/master/src/util/handlers.js). If not, i'll probably get to it sometime this weekend. Thanks again!

**Comment by mycroft11** [comment]
in 4.3.1 orientation is being set to "(orientation: landscape)" instead of "landscape"

**Comment by AlecAivazis** [comment]
@mycroft11 @VeeteshJain after thinking about this for awhile, i'm very tempted to just remove orientation from the default responsive state all-together (since I did the same for `browser.width`). I'm not too keen on a major version bump, so I'll probably add a deprecation warning to `orientation` and remove it in the next major version.

**Comment by AlecAivazis** [comment]
Unfortunately, fixing the typo @mycroft11 reported is technically an API breaking change since one could not safely use the fixed value, so I think rather than fixing either of these issues, i'm going to remove it from the default responsive state and instead refer @VeeteshJain to the documentation for adding custom fields and event handlers to track them.

**Comment by AlecAivazis** [comment]
Scratch that, after looking around at what it takes to reliably compute the orientation, i think im going to keep things the way they are for now and instead treat the issue reported by @mycroft11 as a bug and only bump a patch version since both of these were originally intended features.

**Comment by AlecAivazis** [comment]
Orientation should now be updating as expected with the merge of #80
