### ISSUE TITLE
extend Immutable.js support

### ISSUE THREAD

**Issue by bguggie** [AlecAivazis/redux-responsive#83]
Currently getBreakpoints does not handle Immutable store having data stored in an Immutable Map

**Comment by shanecav** [comment]
@AlecAivazis this issue is still valid - I'll submit a PR for it today.

**Comment by shanecav** [comment]
Actually, turns out `redux-immutable` should already be working. After talking more with @bguggie it looks like this issue was related to a more specific problem with the way they were transforming the entire state into Immutable data before hydrating (when using SSR).

I added a couple tests to improve coverage in that area, and updated the readme with a quick note about `redux-immutable` usage to help people avoid this issue in the future (PR #86).

I think this can be closed @AlecAivazis, but I can look at this again if anyone is still having issues integrating with `redux-immutable`.

**Comment by AlecAivazis** [comment]
I'm going to close this since #86 has been merged. Thanks again @bguggie  and @shanecav!
