### ISSUE TITLE
What's the difference between `mediaType` and the `is` booleans?

### ISSUE THREAD

**Issue by codepunkt** [AlecAivazis/redux-responsive#91]
Aren't those redundant values?
Every time the boolean in the `is` object changes, the `mediaType` changes aswell?

I'm just asking to understand what part of my state i'll use.

**Comment by AlecAivazis** [comment]
Hey @codepunkt  - sorry it took me a while to get back to you. These two fields have very similar purposes and which you should use really depends on your particular use case. In general, the two are equivalent. 

I find that `is` is best for Boolean checks against a particular media type, for example

```es6
const brandingLogo = browser.is.small ? <small_logo> : <large_logo>
```

Whereas `mediaType` is good for situations where you need to do something more complicated than above, for example if you had many logos depending on the breakpoint

```es6
const brandingLogo = { 
    small: <small_logo>,
    medium: <medium_logo>,
    large: <large_logo>
}[browser.mediaType]
```

For full context, `mediaType` was part of the very first API and `is` was suggested later in order to make checks against `mediaType` more like the other breakpoints. When `is` was added, I didn't want to break the public API so I left the two. Also, without `mediaType`, finding the current breakpoint for non-Boolean statements would be a simple, but boilerplate-y reduce to find the key with the `true` value.

**Comment by codepunkt** [comment]
Thanks, Alec! That explains it very well.
