### ISSUE TITLE
Wrong TypeScript definition for extraFields

### ISSUE THREAD

**Issue by chrumck** [AlecAivazis/redux-responsive#98]
It seems the [TS Definition for extraFields](https://github.com/AlecAivazis/redux-responsive/blob/a3d6d445f319e125d58bdee0b94bf6bd0867762d/types/index.d.ts#L31) does not match the documentation. Shouldn't it be this instead?:
`extraFields?(responsiveState?: IBrowser<BP>): any;`

**Comment by AlecAivazis** [comment]
Thanks for reporting this @chrumck. I've been relying on the community to maintain these type definitions since I have never used it in a project before. However, from what I do understand of the syntax, your definition does make sense. I can subit a PR with this small change but I'd also like to make sure that non of the other definitions are incorrect - is that the only inconsistency you've found?

**Comment by chrumck** [comment]
Yes, that's the only one I've found, but I wasn't looking hard :smile:

**Comment by deadNightTiger** [comment]
Actually there are more issues with this option. Right now fields from `extraFields` would not be present in the `IBrowser` type, so it would not be accessible without some casting. I might work on this in some free time soon.

**Comment by chrumck** [comment]
@deadNightTiger The way I personally addressed adding extra fields is extending IBrowser like this:
`export interface BrowserCustomFields {width: number;height: number;}`
`export interface MyBrowser extends IBrowser, BrowserCustomFields { }`
and using the extended IBrowser to declare a prop on the state. 

But I guess you are right that making IBrowser generic on some type like TExtraFields and have extraFields return this type would be better.

**Comment by AlecAivazis** [comment]
Closing this since #100 addressed it and the changes have been published under version `4.3.6`
